sudo: false
language: scala

before_install:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.3.6/0.3.6-85-38fce6 && chmod +x ~/bin/mill

script:
- mill __[$TRAVIS_SCALA_VERSION].test

jobs:
  include:
    - scala: 2.11.12
    - scala: 2.12.7
    - scala: 2.13.0-RC1
